uebung_4_loesung/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :movies

end

uebung_4_loesung/app/models/movie.rb
class Movie < ActiveRecord::Base
end

uebung_4_loesung/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

uebung_4_loesung/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
  end

  def create
    @movie = Movie.new(movie_params)

    @movie.save
    redirect_to @movie
  end

private
      def movie_params
        params.require(:movie).permit(:title, :director, :year)
      end
end

uebung_4_loesung/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

uebung_4_loesung/app/helpers/application_helper.rb
module ApplicationHelper
end

uebung_4_loesung/app/helpers/movies_helper.rb
module MoviesHelper
end

uebung_4_loesung/app/helpers/welcome_helper.rb
module WelcomeHelper
end

uebung_4_loesung/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieDB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

uebung_4_loesung/app/views/movies/index.html.erb
<h1> Movies </h1>
<table>
  <tr>
    <th> Title </th>
    <th> Director </th>
    <th> Year </th>
  </tr>

  <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.title %></td>
      <td><%= movie.director %></td>
      <td><%= movie.year %></td>
    </tr>
  <% end %>
</table>

uebung_4_loesung/app/views/movies/new.html.erb
<h1> New Movie </h1>
<%= form_for :movie, url: movies_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </p>

  <p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

uebung_4_loesung/app/views/movies/show.html.erb
<p>
  <strong> Title: </strong>
  <%= @movie.title %>
</p>

<p>
  <strong> Director: </strong>
  <%= @movie.director %>
</p>

<p>
  <strong> Year: </strong>
  <%= @movie.year %>
</p>

uebung_4_loesung/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>